"""empty message

Revision ID: 32ce9e0868ed
Revises: a94403b1d18b
Create Date: 2023-09-01 23:54:44.413664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ce9e0868ed'
down_revision = 'a94403b1d18b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.String(length=30), nullable=False),
    sa.Column('rotation_period', sa.String(length=30), nullable=False),
    sa.Column('orbital_period', sa.String(length=30), nullable=False),
    sa.Column('gravity', sa.String(length=30), nullable=False),
    sa.Column('population', sa.String(length=30), nullable=False),
    sa.Column('climate', sa.String(length=30), nullable=False),
    sa.Column('terrain', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_name', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=True),
    sa.Column('cost_in_credits', sa.String(length=50), nullable=True),
    sa.Column('length', sa.String(length=50), nullable=True),
    sa.Column('max_atmosphering_speed', sa.String(length=50), nullable=True),
    sa.Column('crew_id', sa.String(length=50), nullable=True),
    sa.Column('passengers_id', sa.String(length=50), nullable=True),
    sa.Column('cargo_capacity', sa.String(length=50), nullable=True),
    sa.Column('consumables', sa.String(length=50), nullable=True),
    sa.Column('vehicle_class', sa.String(length=50), nullable=True),
    sa.Column('pilots_id', sa.String(length=50), nullable=True),
    sa.Column('films', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicles')
    op.drop_table('planets')
    # ### end Alembic commands ###
