"""empty message

Revision ID: 7453ff12a0be
Revises: 32ce9e0868ed
Create Date: 2023-09-02 00:30:34.981964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7453ff12a0be'
down_revision = '32ce9e0868ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_name', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_column('planet_name')

    # ### end Alembic commands ###
