"""empty message

Revision ID: ef20176b0b44
Revises: 7453ff12a0be
Create Date: 2023-09-02 00:41:59.967073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef20176b0b44'
down_revision = '7453ff12a0be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('films')
        batch_op.drop_column('pilots_id')
        batch_op.drop_column('crew_id')
        batch_op.drop_column('passengers_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passengers_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('crew_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pilots_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('films', sa.VARCHAR(length=50), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
